docs: add notice and rebrand
aztfmod/documentation pull request #62
Opened 2024-01-26 08:42 UTC by matt-FFFFFF

2024-01-31 03:04 UTC, LaurentLesle requested changes
See my comments

2024-01-31 03:04 UTC, LaurentLesle commented on website/docusaurus.config.js
> -                href: 'https://github.com/azure/caf-terraform-landingzones',
See comment earlier on the name

2024-01-31 03:04 UTC, LaurentLesle commented on website/versioned_docs/version-2203.1/azure-landing-zones/landingzones/platform/files_reference.md
> -| caf_landingzone_branch            | yes      | tag or branch name                    | Release number from the repo https://github.com/Azure/caf-terraform-landingzones/releases
See comments on name

2024-03-11 08:47 UTC, LaurentLesle commented on website/docs/azure-landing-zones/landingzones/platform/org-setup.mdx
> -The [platform starter project is here](https://github.com/Azure/caf-terraform-landingzones-platform-starter).
archived already

2024-05-29 08:32 UTC, arnaudlh commented
Closing as changes already implemented.

2024-05-29 08:32 UTC, closed without merging